### ISSUE TITLE
Patch for /src/com/farproc/wifi/connecter/TestWifiScan.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mkch/android-wifi-connecter#9]
```
<program> Copyright (C) <year> <name of author> This program comes with 
ABSOLUTELY NO WARRANTY; for details type `show w'. This is free software, and 
you are welcome to redistribute it under certain conditions; type `show c' for 
details.
```

Original issue reported on code.google.com by `ultimase...@gmail.com` on 17 Jul 2013 at 4:36

Attachments:
- [TestWifiScan.java.patch](https://storage.googleapis.com/google-code-attachments/android-wifi-connecter/issue-9/comment-0/TestWifiScan.java.patch)

**Comment by 9732bob** [comment]
How does it work?

**Comment by ghelie** [comment]
Wifi please back connection

**Comment by StLouisMan2** [comment]
I came here to get the WiFi connector for the WiFi analyzer app. Where is it? What do I download? I think you should make this more obvious for someone who may not be so tech savvy. Garbage.

**Comment by abdomorse** [comment]
اريد اخترق اي شبكة واي فاي

**Comment by morecrazynights21** [comment]
Good

**Comment by Tmen77** [comment]
Tmenovi

**Comment by edyvanellende** [comment]
Is something wrong
